<a href="https://colab.research.google.com/github/santhosh1982/Youtube-Pytorch-Tutorial/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])


In [4]:
tensor_a - tensor_b

tensor([-5, -5, -5, -5, -5])

In [5]:
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [6]:
m = torch.mul(tensor_a,tensor_b)
m

tensor([ 6, 14, 24, 36, 50])

In [7]:
tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])

In [8]:
tensor_a / tensor_b

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [9]:
torch.div(tensor_a, tensor_b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [11]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1, 0])

In [12]:
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [13]:
tensor_a.add(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [16]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([19, 23, 27, 31, 35])